/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F407DISC.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
  STRUCT_GPIO_HANDLER  Green;

		/* initializing ALL GOOD LED on GPIOD */
	Green.pGPIOx = GPIOD;
	Green.GPIO_PinConfig.GPIO_PinNumber 		= GPIO_PIN_NO_12;
	Green.GPIO_PinConfig.GPIO_PinMode  			= GPIO_MODE_OP;
	Green.GPIO_PinConfig.GPIO_PinOPType 		= GPIO_OP_TYPE_PP;
	Green.GPIO_PinConfig.GPIO_PinPuPdControl 	= GPIO_NO_PUPD;

	GPIO_PClkCtrl(GPIOD,ENABLE);
	GPIO_Init(&Green);



	while(1)
	{
		GPIO_Toggle(GPIOD, GPIO_PIN_NO_12);

	}
}
